### ISSUE TITLE
App Store Guideline Changes to allow Retro Emulators

### ISSUE THREAD

**Issue by yemibox51** [rileytestut/Delta#293] opened 2024-04-05 22:53 UTC
Per Apple's new guideline changes globally, would Delta Emulator allowed to come directly to the app store?

> 4.7: Added games from retro game console emulator apps to the list of permitted software, and clarifies that mini apps and mini games must be HTML5.

Full link to [App Store Review Guidelines: Retro Game Emulators](https://developer.apple.com/app-store/review/guidelines/#:~:text=new%20springboard%20icon.-,4.7%20Mini%20apps%2C%20mini%20games%2C%20streaming%20games%2C%20chatbots%2C%20plug%2Dins%2C%20and%20game%20emulators,-Apps%20may%20offer)

Edit: My guess is probably not, since it does clarify that mini-games must be HTML5. But this stipulation must be met if the app came with software, what if the software is brought from the user like it is here?

**Comment by au5ton** [comment] 2024-04-07 02:53
Dupe of #292

**Closed** 2024-04-07 18:18 UTC
