### ISSUE TITLE
fix xbox one controller support with Ncontrol to enable the use of the joysticks

### ISSUE THREAD

**Issue by cupnoodless** [rileytestut/Delta#22] opened 2019-10-02 05:21 UTC
fix xbox one controller support with Ncontrol to enable the use of the joysticks

**Comment by BSBussell** [comment] 2019-10-02 15:01
Is this possibly a duplicate of #14 ?

**Comment by cupnoodless** [comment] 2019-10-02 16:56
Perhaps, but its my understanding that the mapping works with PS4 controllers, and just not the xbox one controllers. Also, is there a way to map diagonal button movements with the directional pad for the nes, SNES, and gba? It's hard to throw a fireball without the diagonal button. Is there a way to implement a diagonal button movement? Thanks for getting back to me. I think this is different than #14 because I wondered if you could use the joysticks on nes, gba, and sees also.

**Closed** 2023-03-17 16:57 UTC
